language: "python"
services:
    - "mysql"
    - "redis-server"
python:
    - "2.7"
install:
    - export LIBGIT2=$VIRTUAL_ENV
    - wget https://github.com/libgit2/libgit2/archive/v0.22.0.tar.gz
    - tar xzf v0.22.0.tar.gz
    - cd libgit2-0.22.0/
    - cmake . -DCMAKE_INSTALL_PREFIX=$LIBGIT2
    - make && make install
    - cd ..
    - export LDFLAGS="-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS"
    - pip install pytest
    - pip install -r requirements.txt
script: "py.test tests"
before_script:
    - "mysql -e 'create database erutest;' -uroot"
